// examples/preact/src/app.tsx
import { effect, signal } from '@preact/signals'

import * as Cesium from 'cesium'
import 'cesium/Build/Cesium/Widgets/widgets.css'

export function App() {
  const container = signal<HTMLElement | null>(null)

  effect(() => {
    if (!container.value)
      return

    /* eslint-disable no-new */
    new Cesium.Viewer(container.value!)
  })

  return (
    <div ref={el => container.value = el} style={{ width: '100vw', height: '100vh' }} />
  )
}

// examples/solid/src/App.tsx
import * as Cesium from 'cesium'
import { onMount } from 'solid-js'
import 'cesium/Build/Cesium/Widgets/widgets.css'

function App() {
  let container: HTMLDivElement | undefined

  onMount(() => {
    /* eslint-disable no-new */
    new Cesium.Viewer(container!)
  })

  return (
    <div ref={container} />
  )
}

export default App
