// examples/svelte/src/App.svelte
<script lang="ts">
import { onMount } from 'svelte'
import * as Cesium from 'cesium'
import 'cesium/Build/Cesium/Widgets/widgets.css'

let container:null

onMount(() => {
  if(!container)
    return

  const v = new Cesium.Viewer(container)

  return () => v.destroy()
})
</script>

<div bind:this={container} />

// examples/solid/src/App.tsx
import * as Cesium from 'cesium'
import 'cesium/Build/Cesium/Widgets/widgets.css'
import { onMount } from 'solid-js'

function App() {
  let container: HTMLDivElement | undefined

  onMount(() => {
    new Cesium.Viewer(container!)
  })

  return (
    <div ref={container} />
  )
}

export default App
